# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpressimport',
            name='json',
        ),
        migrations.AddField(
            model_name='wordpressimport',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordpressimport',
            name='user',
            field=models.ForeignKey(default=1, help_text='News items will be created with this user as the owner.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordpressimport',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordpressimport',
            name='url',
            field=models.URLField(help_text='Base URL eg. https://janeway.systems', verbose_name='URL'),
        ),
    ]
