# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0041_issue_short_description'),
        ('submission', '0052_auto_20210525_1743'),
        ('imports', '0002_auto_20190829_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJS3Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojs_id', models.IntegerField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.Section')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ojs3section',
            unique_together=set([('ojs_id', 'journal'), ('ojs_id', 'section')]),
        ),
    ]
