# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-05 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0045_auto_20210721_1212'),
        ('imports', '0003_auto_20210624_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJSAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojs_id', models.IntegerField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ojsaccount',
            unique_together=set([('ojs_id', 'journal', 'account')]),
        ),
    ]
