# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0041_issue_short_description'),
        ('core', '0050_xslt_1-3-10'),
        ('submission', '0051_auto_20210222_1452'),
        ('imports', '0003_exportfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exportfile',
            unique_together=set([('article', 'file', 'journal')]),
        ),
    ]
