# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-13 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_auto_20210805_1149'),
        ('imports', '0004_auto_20210525_1114'),
    ]

    operations = [
    ]
