# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0066_article_issn_override'),
        ('imports', '0005_merge_20210913_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='CSVImportCreateArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CSVImportUpdateArticle',
            fields=[
                ('csvimportcreatearticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imports.CSVImportCreateArticle')),
            ],
            bases=('imports.csvimportcreatearticle',),
        ),
        migrations.AddField(
            model_name='csvimportcreatearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article'),
        ),
        migrations.AddField(
            model_name='csvimportcreatearticle',
            name='csv_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.CSVImport'),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='updated_articles',
            field=models.ManyToManyField(blank=True, related_name='csv_import_updates', through='imports.CSVImportCreateArticle', to='submission.Article'),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='created_articles',
            field=models.ManyToManyField(blank=True, related_name='csv_import_creation', through='imports.CSVImportUpdateArticle', to='submission.Article'),
        ),
    ]
