# Generated by Django 3.2.20 on 2023-11-06 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_merge_20231025_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imports', '0007_csvimportcreatearticle_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojs3section',
            name='ojs_ref',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='csvimportcreatearticle',
            name='csv_import',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.csvimport'),
        ),
        migrations.AlterField(
            model_name='ojs3section',
            name='ojs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ojsaccount',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OJSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojs_id', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
    ]
