# Generated by Django 3.2.20 on 2024-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_auto_20231106_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedImportNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of user to receive notification of automatic import logs.', max_length=254)),
            ],
        ),
    ]
