# Generated by Django 4.2.20 on 2025-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_auto_20231106_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojs3section',
            name='ojs_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
