"""Command line interface for the WordPress WXR importer.

Usage:

    python manage.py import_wordpress <journal_code> <path_to_export.xml>
    python manage.py import_wordpress code path/to/export/xml --dry-run
    python manage.py import_wordpress code path/to/export/xml \
        --exclude in-italian --exclude "Featured Books"
    python manage.py import_wordpress code path/to/export/xml --only 3712
    python manage.py import_wordpress code path/to/export/xml \
        --live-order --download-pdfs --download-images

See plugins.imports.wordpress for the import itself.
"""

import os

from django.core.management.base import BaseCommand, CommandError

from journal import models as journal_models
from plugins.imports import wordpress


class Command(BaseCommand):
    help = "Import articles, issues, pages and authors from a WordPress WXR export."

    def add_arguments(self, parser):
        parser.add_argument(
            "journal_code", help="Code of the target journal (e.g. ejp)"
        )
        parser.add_argument("xml_path", help="Path to the WordPress export XML file")
        parser.add_argument(
            "--exclude",
            action="append",
            default=[],
            metavar="TOKEN",
            help="Skip articles matching TOKEN (repeatable, case-insensitive)."
            " A token can be a category slug or name (e.g. 'in-italian',"
            " 'In Italian'), a collection/issue parent post's WordPress id,"
            " slug or title (e.g. 'Featured Books'), or an article's"
            " WordPress id, slug or title.",
        )
        parser.add_argument(
            "--only",
            action="append",
            default=[],
            metavar="TOKEN",
            help="Import only articles matching TOKEN (repeatable). Accepts"
            " the same tokens as --exclude, e.g. a single collection title"
            " or a single article's WordPress id. --exclude still applies"
            " on top.",
        )
        parser.add_argument(
            "--include-unpublished",
            action="store_true",
            help="Also import draft/private posts (as unsubmitted articles)",
        )
        parser.add_argument(
            "--download-pdfs",
            action="store_true",
            help="Download the PDF files uploaded to each article from the"
            " live site and attach them as galleys",
        )
        parser.add_argument(
            "--download-images",
            action="store_true",
            help="Download the images embedded in article bodies from the"
            " WordPress site, store them against the HTML galley and point"
            " the <img> tags at the stored copies (needed when the"
            " WordPress site is going away)",
        )
        parser.add_argument(
            "--download-autogenerated-pdfs",
            action="store_true",
            help="Download the PDF the WordPress theme generates for each"
            " article (the site's 'download PDF' link, rendered on request)"
            " and attach it as a PDF galley",
        )
        parser.add_argument(
            "--theme",
            default=None,
            metavar="NAME",
            help="Directory name of the WordPress theme whose pdf.php generates"
            " the article PDFs. When omitted it is read from the 'download"
            " PDF' link of a live article page; if that fails too, the"
            " autogenerated PDFs are skipped with a warning.",
        )
        parser.add_argument(
            "--live-order",
            action="store_true",
            help="Fetch each issue/collection page from the live WordPress"
            " site and reproduce the order in which it lists its articles."
            " The export does not contain this manual order; without this"
            " flag articles are listed newest first.",
        )
        parser.add_argument(
            "--skip-pages",
            action="store_true",
            help="Do not import WordPress pages (About, Submissions...) as"
            " CMS pages and navigation items",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Parse and report what would be imported, then roll everything"
            " back. Galley files, PDFs and images are neither written nor"
            " deleted.",
        )

    def handle(self, *args, **options):
        try:
            journal = journal_models.Journal.objects.get(code=options["journal_code"])
        except journal_models.Journal.DoesNotExist:
            raise CommandError(
                "No journal with code '{}' found.".format(options["journal_code"])
            )
        if not os.path.isfile(options["xml_path"]):
            raise CommandError("Export file not found: {}".format(options["xml_path"]))

        stats = wordpress.import_wordpress_export(
            journal,
            options["xml_path"],
            stdout=self.stdout,
            dry_run=options["dry_run"],
            include_unpublished=options["include_unpublished"],
            download_pdfs=options["download_pdfs"],
            download_images=options["download_images"],
            download_autogenerated_pdfs=options["download_autogenerated_pdfs"],
            theme=options["theme"],
            live_order=options["live_order"],
            skip_pages=options["skip_pages"],
            exclude=options["exclude"],
            only=options["only"],
        )

        self.stdout.write("\nSummary:")
        for key, value in sorted(stats.items()):
            self.stdout.write("  {}: {}".format(key.replace("_", " "), value))
